### ISSUE TITLE
Update AAGI horizontal logo

### ISSUE THREAD

**Issue by rogerssam** [biometryhub/AAGITemplates#3]
For presentations

**Comment by RussellAndrewEdson** [comment]
I reckon we're good to go with this using the ones I quickly drew up yesterday (e.g. ![here](https://github.com/biometryhub/AAGITemplates/blob/a9a9e9beb565c2659a10c1509edd2498b882fd11/inst/rmarkdown/templates/HTML_presentation/skeleton/assets/partners.jpg) and ![here for the project partner one](https://github.com/biometryhub/AAGITemplates/blob/a9a9e9beb565c2659a10c1509edd2498b882fd11/inst/rmarkdown/templates/HTML_presentation/skeleton/assets/project_partner.jpg). Those are jpgs, but I've still got the GIMP xcf's around that can generate the others, and I'll upload everything to the AAGI Box at some point later today.
